use crate::{html_parse, neum_parse, ARGS};
use itertools::Itertools;
use std::ffi::OsStr;
use std::fs::File;
use std::io::Write;
use std::path::Component;
use std::sync::{Arc, Mutex};
use std::time::Instant;

lazy_static::lazy_static! {
    static ref REAL_DEFAULTS: Arc<neum::Neum> = Arc::new(neum::Neum::default());
    static ref DEFAULTS: Arc<Mutex<neum::Neum>> = Arc::new(Mutex::new(neum::Neum::default()));
}

pub fn update(refresh: bool) {
    let mut now = Instant::now();
    let mut output = String::from("/* auto generated by Neum https://github.com/AMTitan/Neum */\n");
    let html = html_parse::HTML_FILES.lock().unwrap();
    let mut neum_files = neum_parse::NEUM_FILES.lock().unwrap();

    let mut total_classes = Vec::new();
    for (_, i) in html.iter() {
        total_classes.append(&mut i.clone());
    }
    total_classes = total_classes
        .iter()
        .unique()
        .cloned()
        .collect::<Vec<String>>();

    let mut total_neum = DEFAULTS.lock().unwrap();
    if refresh {
        let mut libraries = neum::Neum::empty();
        let mut other = neum::Neum::empty();

        for (path, neum) in neum_files.iter_mut() {
            if path
                .as_path()
                .components()
                .any(|x| x == Component::Normal(OsStr::new(".neum")))
            {
                libraries.combine_priority(neum);
            } else {
                other.combine_priority(neum);
            }
        }

        *total_neum = (*REAL_DEFAULTS.clone()).clone();
        total_neum.combine_priority(&mut libraries);
        total_neum.combine_priority(&mut other);

        total_neum.refresh();

        if ARGS.verbose {
            println!("Updated neum definitions in {:?}", now.elapsed());
        }
        now = Instant::now();
    }

    for i in total_classes {
        if let Some(mut x) = total_neum.convert(i.clone()) {
            while x.starts_with('.') || x.starts_with('@') {
                let period = x.starts_with('.');
                let mut split = x.split('}').collect::<Vec<_>>();
                let mut new_css = format!("{}}}", split.remove(0));
                if period && new_css.split('{').next().unwrap().contains(':') {
                    let mut vec = new_css.split(':').collect::<Vec<_>>();
                    let first = &format!(".{i}");
                    vec[0] = first;
                    new_css = vec.join(":");
                }
                output.push_str(&new_css);
                x = split.join("}");
            }
            if x != ";" {
                output.push_str(&format!(".{i}{{{x}}}"));
            }
        }
    }
    let mut file = File::create(ARGS.output.clone().unwrap()).unwrap();
    file.write_all(output.as_bytes()).unwrap();
    if ARGS.verbose {
        println!("Generated css in {:?}", now.elapsed());
    }
}
